version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - edipnet

  myapp:
    image: medipnegiz/bookstore-api:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    networks:
      - edipnet
    ports:
      - "80:80"

networks:
  edipnet:
    driver: bridge

# volumes:
