apiVersion: v1
kind: Service
metadata:
  name: resultserver-service
  labels:
    app: resultserver-deploy
spec:
  type: NodePort
  selector:
    app: resultserver-deploy
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
    protocol: TCP
    name: resultserver-port
