apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    app: webserver-deploy
spec:
  type: NodePort
  selector:
    app: webserver-deploy
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
    protocol: TCP
    name: webserver-port
